# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: waste-api-service
spec:
  type: NodePort
  selector:
    app: waste-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
